// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NPAInspectionWriter.AppData {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NPAInspectionWriter.AppData.AppMessages", typeof(AppMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BlankPasswordErrorMessage {
            get {
                return ResourceManager.GetString("BlankPasswordErrorMessage", resourceCulture);
            }
        }
        
        internal static string BlankUserNameErrorMessage {
            get {
                return ResourceManager.GetString("BlankUserNameErrorMessage", resourceCulture);
            }
        }
        
        internal static string ConnectivityWarningMessage {
            get {
                return ResourceManager.GetString("ConnectivityWarningMessage", resourceCulture);
            }
        }
        
        internal static string CurrentInspectionNotFoundMessage {
            get {
                return ResourceManager.GetString("CurrentInspectionNotFoundMessage", resourceCulture);
            }
        }
        
        internal static string DatabaseLockedMessage {
            get {
                return ResourceManager.GetString("DatabaseLockedMessage", resourceCulture);
            }
        }
        
        internal static string EmailSentMessage {
            get {
                return ResourceManager.GetString("EmailSentMessage", resourceCulture);
            }
        }
        
        internal static string ExpiredLoginMessage {
            get {
                return ResourceManager.GetString("ExpiredLoginMessage", resourceCulture);
            }
        }
        
        internal static string InvalidStockNumber {
            get {
                return ResourceManager.GetString("InvalidStockNumber", resourceCulture);
            }
        }
        
        internal static string InvalidVIN {
            get {
                return ResourceManager.GetString("InvalidVIN", resourceCulture);
            }
        }
        
        internal static string MatrixGlitchErrorMessage {
            get {
                return ResourceManager.GetString("MatrixGlitchErrorMessage", resourceCulture);
            }
        }
        
        internal static string NoCameraOnDeviceMessage {
            get {
                return ResourceManager.GetString("NoCameraOnDeviceMessage", resourceCulture);
            }
        }
        
        internal static string NoInspectionTypesAvailableMessage {
            get {
                return ResourceManager.GetString("NoInspectionTypesAvailableMessage", resourceCulture);
            }
        }
        
        internal static string NoMastersAvailableMessage {
            get {
                return ResourceManager.GetString("NoMastersAvailableMessage", resourceCulture);
            }
        }
        
        internal static string NoMasterSelectedMessage {
            get {
                return ResourceManager.GetString("NoMasterSelectedMessage", resourceCulture);
            }
        }
        
        internal static string NoPrintersAvailable {
            get {
                return ResourceManager.GetString("NoPrintersAvailable", resourceCulture);
            }
        }
        
        internal static string OfflineErrorMessage {
            get {
                return ResourceManager.GetString("OfflineErrorMessage", resourceCulture);
            }
        }
        
        internal static string RequiredAppUpdateErrorMessage {
            get {
                return ResourceManager.GetString("RequiredAppUpdateErrorMessage", resourceCulture);
            }
        }
        
        internal static string SelectPrinterLabelType {
            get {
                return ResourceManager.GetString("SelectPrinterLabelType", resourceCulture);
            }
        }
        
        internal static string StandardErrorMessage {
            get {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }
        
        internal static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        internal static string UnauthorizedLoginMessage {
            get {
                return ResourceManager.GetString("UnauthorizedLoginMessage", resourceCulture);
            }
        }
        
        internal static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        internal static string VehicleNotFoundMessage {
            get {
                return ResourceManager.GetString("VehicleNotFoundMessage", resourceCulture);
            }
        }
        
        internal static string UpdateMessageFormat {
            get {
                return ResourceManager.GetString("UpdateMessageFormat", resourceCulture);
            }
        }
        
        internal static string VehicleNotFoundSearchMessage {
            get {
                return ResourceManager.GetString("VehicleNotFoundSearchMessage", resourceCulture);
            }
        }
        
        internal static string ExpiredSessionMessage {
            get {
                return ResourceManager.GetString("ExpiredSessionMessage", resourceCulture);
            }
        }
        
        internal static string NoInspectionImages {
            get {
                return ResourceManager.GetString("NoInspectionImages", resourceCulture);
            }
        }
        
        internal static string DeleteInspection {
            get {
                return ResourceManager.GetString("DeleteInspection", resourceCulture);
            }
        }
    }
}
