// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NPAInspectionWriter.AppData {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NPAInspectionWriter.AppData.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConnectivityWarningAlertTitle {
            get {
                return ResourceManager.GetString("ConnectivityWarningAlertTitle", resourceCulture);
            }
        }
        
        internal static string DismissButtonText {
            get {
                return ResourceManager.GetString("DismissButtonText", resourceCulture);
            }
        }
        
        internal static string EnterStockNumber {
            get {
                return ResourceManager.GetString("EnterStockNumber", resourceCulture);
            }
        }
        
        internal static string EnterVin {
            get {
                return ResourceManager.GetString("EnterVin", resourceCulture);
            }
        }
        
        internal static string LocalInspectionsBtnText {
            get {
                return ResourceManager.GetString("LocalInspectionsBtnText", resourceCulture);
            }
        }
        
        internal static string MessageFailureAlert {
            get {
                return ResourceManager.GetString("MessageFailureAlert", resourceCulture);
            }
        }
        
        internal static string OfflineAlertTitle {
            get {
                return ResourceManager.GetString("OfflineAlertTitle", resourceCulture);
            }
        }
        
        internal static string OhSnapAlertTitle {
            get {
                return ResourceManager.GetString("OhSnapAlertTitle", resourceCulture);
            }
        }
        
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        internal static string ScanBarcodeBtnText {
            get {
                return ResourceManager.GetString("ScanBarcodeBtnText", resourceCulture);
            }
        }
        
        internal static string StockNumberEnumDescription {
            get {
                return ResourceManager.GetString("StockNumberEnumDescription", resourceCulture);
            }
        }
        
        internal static string SuccessAlertTitle {
            get {
                return ResourceManager.GetString("SuccessAlertTitle", resourceCulture);
            }
        }
        
        internal static string VehicleAlertsTitle {
            get {
                return ResourceManager.GetString("VehicleAlertsTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailCommentsTitle {
            get {
                return ResourceManager.GetString("VehicleDetailCommentsTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailInspectionsTitle {
            get {
                return ResourceManager.GetString("VehicleDetailInspectionsTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailSendEmailPageTitle {
            get {
                return ResourceManager.GetString("VehicleDetailSendEmailPageTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailsPageTitle {
            get {
                return ResourceManager.GetString("VehicleDetailsPageTitle", resourceCulture);
            }
        }
        
        internal static string VehicleSearchTitle {
            get {
                return ResourceManager.GetString("VehicleSearchTitle", resourceCulture);
            }
        }
        
        internal static string VINAlertsTitle {
            get {
                return ResourceManager.GetString("VINAlertsTitle", resourceCulture);
            }
        }
        
        internal static string VinEnumDescription {
            get {
                return ResourceManager.GetString("VinEnumDescription", resourceCulture);
            }
        }
        
        internal static string WhoopsAlertTitle {
            get {
                return ResourceManager.GetString("WhoopsAlertTitle", resourceCulture);
            }
        }
        
        internal static string LocalInspectionsPageTitle {
            get {
                return ResourceManager.GetString("LocalInspectionsPageTitle", resourceCulture);
            }
        }
        
        internal static string InspectionOverviewPageTitle {
            get {
                return ResourceManager.GetString("InspectionOverviewPageTitle", resourceCulture);
            }
        }
        
        internal static string SearchStockNumberPlaceholder {
            get {
                return ResourceManager.GetString("SearchStockNumberPlaceholder", resourceCulture);
            }
        }
        
        internal static string SearchVinPlaceholder {
            get {
                return ResourceManager.GetString("SearchVinPlaceholder", resourceCulture);
            }
        }
        
        internal static string ChoosePrinterActionSheetTitle {
            get {
                return ResourceManager.GetString("ChoosePrinterActionSheetTitle", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        internal static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        internal static string ImageGalleryPageTitle {
            get {
                return ResourceManager.GetString("ImageGalleryPageTitle", resourceCulture);
            }
        }
        
        internal static string InsertVehicleInfo {
            get {
                return ResourceManager.GetString("InsertVehicleInfo", resourceCulture);
            }
        }
        
        internal static string InspectionCommentsSectionTitle {
            get {
                return ResourceManager.GetString("InspectionCommentsSectionTitle", resourceCulture);
            }
        }
        
        internal static string InspectionMasterSectionTitle {
            get {
                return ResourceManager.GetString("InspectionMasterSectionTitle", resourceCulture);
            }
        }
        
        internal static string InspectionOpenRepairs {
            get {
                return ResourceManager.GetString("InspectionOpenRepairs", resourceCulture);
            }
        }
        
        internal static string InspectionTypeSectionTitle {
            get {
                return ResourceManager.GetString("InspectionTypeSectionTitle", resourceCulture);
            }
        }
        
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        internal static string LogoutToolbarText {
            get {
                return ResourceManager.GetString("LogoutToolbarText", resourceCulture);
            }
        }
        
        internal static string RepairsSectionTitle {
            get {
                return ResourceManager.GetString("RepairsSectionTitle", resourceCulture);
            }
        }
        
        internal static string SearchBtnText {
            get {
                return ResourceManager.GetString("SearchBtnText", resourceCulture);
            }
        }
        
        internal static string SubmitBtnText {
            get {
                return ResourceManager.GetString("SubmitBtnText", resourceCulture);
            }
        }
        
        internal static string VehicleAuctioneerNotesTitle {
            get {
                return ResourceManager.GetString("VehicleAuctioneerNotesTitle", resourceCulture);
            }
        }
        
        internal static string VehicleCommentsTitle {
            get {
                return ResourceManager.GetString("VehicleCommentsTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailColor {
            get {
                return ResourceManager.GetString("VehicleDetailColor", resourceCulture);
            }
        }
        
        internal static string VehicleDetailMake {
            get {
                return ResourceManager.GetString("VehicleDetailMake", resourceCulture);
            }
        }
        
        internal static string VehicleDetailMilesHours {
            get {
                return ResourceManager.GetString("VehicleDetailMilesHours", resourceCulture);
            }
        }
        
        internal static string VehicleDetailModel {
            get {
                return ResourceManager.GetString("VehicleDetailModel", resourceCulture);
            }
        }
        
        internal static string VehicleDetailSectionTitle {
            get {
                return ResourceManager.GetString("VehicleDetailSectionTitle", resourceCulture);
            }
        }
        
        internal static string VehicleDetailSize {
            get {
                return ResourceManager.GetString("VehicleDetailSize", resourceCulture);
            }
        }
        
        internal static string VehicleDetailStockNumber {
            get {
                return ResourceManager.GetString("VehicleDetailStockNumber", resourceCulture);
            }
        }
        
        internal static string VehicleDetailVIN {
            get {
                return ResourceManager.GetString("VehicleDetailVIN", resourceCulture);
            }
        }
        
        internal static string VehicleDetailYear {
            get {
                return ResourceManager.GetString("VehicleDetailYear", resourceCulture);
            }
        }
        
        internal static string VehiclePublicAuctionNotesTitle {
            get {
                return ResourceManager.GetString("VehiclePublicAuctionNotesTitle", resourceCulture);
            }
        }
        
        internal static string VehicleRepairCommentsTitle {
            get {
                return ResourceManager.GetString("VehicleRepairCommentsTitle", resourceCulture);
            }
        }
        
        internal static string ImageViewPageTitle {
            get {
                return ResourceManager.GetString("ImageViewPageTitle", resourceCulture);
            }
        }
        
        internal static string InspectionOptionsPageTitle {
            get {
                return ResourceManager.GetString("InspectionOptionsPageTitle", resourceCulture);
            }
        }
        
        internal static string CancelBtnText {
            get {
                return ResourceManager.GetString("CancelBtnText", resourceCulture);
            }
        }
        
        internal static string SelectInspectionMaster {
            get {
                return ResourceManager.GetString("SelectInspectionMaster", resourceCulture);
            }
        }
        
        internal static string SelectInspectionType {
            get {
                return ResourceManager.GetString("SelectInspectionType", resourceCulture);
            }
        }
        
        internal static string EditingInspectionPageTitle {
            get {
                return ResourceManager.GetString("EditingInspectionPageTitle", resourceCulture);
            }
        }
        
        internal static string LockedInspectionPageTitle {
            get {
                return ResourceManager.GetString("LockedInspectionPageTitle", resourceCulture);
            }
        }
        
        internal static string WarningAlertTitle {
            get {
                return ResourceManager.GetString("WarningAlertTitle", resourceCulture);
            }
        }
        
        internal static string BackMenuOption {
            get {
                return ResourceManager.GetString("BackMenuOption", resourceCulture);
            }
        }
        
        internal static string LoadingAdditionalVehicleDetails {
            get {
                return ResourceManager.GetString("LoadingAdditionalVehicleDetails", resourceCulture);
            }
        }
        
        internal static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
        
        internal static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        internal static string InspectionNotFound {
            get {
                return ResourceManager.GetString("InspectionNotFound", resourceCulture);
            }
        }
        
        internal static string UnratedInspectionOption {
            get {
                return ResourceManager.GetString("UnratedInspectionOption", resourceCulture);
            }
        }
        
        internal static string InspectionStockNumberGrouping {
            get {
                return ResourceManager.GetString("InspectionStockNumberGrouping", resourceCulture);
            }
        }
        
        internal static string LocalInspectionGrouping {
            get {
                return ResourceManager.GetString("LocalInspectionGrouping", resourceCulture);
            }
        }
        
        internal static string CurrentInspectionScore {
            get {
                return ResourceManager.GetString("CurrentInspectionScore", resourceCulture);
            }
        }
        
        internal static string NewInspectionTitle {
            get {
                return ResourceManager.GetString("NewInspectionTitle", resourceCulture);
            }
        }
        
        internal static string PrintLabelTitle {
            get {
                return ResourceManager.GetString("PrintLabelTitle", resourceCulture);
            }
        }
        
        internal static string InstallUpdate {
            get {
                return ResourceManager.GetString("InstallUpdate", resourceCulture);
            }
        }
        
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        internal static string UploadAllMenuOption {
            get {
                return ResourceManager.GetString("UploadAllMenuOption", resourceCulture);
            }
        }
        
        internal static string ChallengeTitle {
            get {
                return ResourceManager.GetString("ChallengeTitle", resourceCulture);
            }
        }
        
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
        
        internal static string NotRated {
            get {
                return ResourceManager.GetString("NotRated", resourceCulture);
            }
        }
        
        internal static string PreviousValueStringFormat {
            get {
                return ResourceManager.GetString("PreviousValueStringFormat", resourceCulture);
            }
        }
        
        internal static string CameraTitle {
            get {
                return ResourceManager.GetString("CameraTitle", resourceCulture);
            }
        }
        
        internal static string PrintLabelSuccess {
            get {
                return ResourceManager.GetString("PrintLabelSuccess", resourceCulture);
            }
        }
        
        internal static string TitleSuccess {
            get {
                return ResourceManager.GetString("TitleSuccess", resourceCulture);
            }
        }
        
        internal static string TitleFail {
            get {
                return ResourceManager.GetString("TitleFail", resourceCulture);
            }
        }
        
        internal static string TitlePrintFail {
            get {
                return ResourceManager.GetString("TitlePrintFail", resourceCulture);
            }
        }
        
        internal static string SelectPrinterMessage {
            get {
                return ResourceManager.GetString("SelectPrinterMessage", resourceCulture);
            }
        }
    }
}
